version: '3.8'

services:
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock_control
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senhadousuario
      TZ: America/Sao_Paulo
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/stock_control.sql:/docker-entrypoint-initdb.d/init.sql
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8091:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

volumes:
  db_data:
